[package]
edition = "2018"
name = "tree"
version = "1.0.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = {version = "0.3", default-features = true}
termion = "1.5.6"
